name: anamnesisai
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python
  - pip
  - poetry
  - nodejs # used by semantic-release
  - shellcheck
  - pip:
      # distlib issue
      - paginate
