name: anamnesisai
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python >=3.9,<3.10
  - pip
  - poetry >=2
  - nodejs # used by semantic-release
  - shellcheck
  - pip:
      # distlib issue
      - paginate
      # pip wheel --no-cache-dir --use-pep517 "srsly (==2.4.8)"
      # note: https://github.com/pypa/virtualenv/issues/2944
      - virtualenv>20.33.1
